# syntax=docker/dockerfile:1

# Alpine is chosen for its small footprint compared to Ubuntu
FROM golang:1.17-alpine AS build-env

ENV GO111MODULE=on
WORKDIR /src

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .
RUN go build -o /microservice



# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env microservice /app/
EXPOSE 9090

CMD [ "/app/microservice" ]